name: Slow Drip Commits (20–30/day, stop after 100 days)

on:
  schedule:
    - cron: "15 1 * * *"   # ทุกวัน 01:15 UTC (≈ 08:15 ไทย)
  workflow_dispatch:         # กด Run เองได้

jobs:
  drip:
    runs-on: ubuntu-latest
    concurrency:
      group: slow-drip
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name  "sphererom"
          git config user.email "134825090+sphererom@users.noreply.github.com"

      # เตรียมไฟล์ตัวนับ + ตัดสินใจหยุดเมื่อครบ 100 วัน
      - name: Prepare counters
        id: prep
        run: |
          mkdir -p .ci
          [ -f .ci/day-count.txt ]   || echo 0 > .ci/day-count.txt
          [ -f .ci/total-commits.txt ] || echo 0 > .ci/total-commits.txt

          DAYS=$(cat .ci/day-count.txt)
          TOTAL=$(cat .ci/total-commits.txt)

          echo "Days so far: $DAYS"
          echo "Total commits so far: $TOTAL"

          if [ "$DAYS" -ge 100 ]; then
            echo "limit=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # สุ่มจำนวนคอมมิตวันนี้ 20–30
          COMMITS=$((20 + RANDOM % 11))
          echo "COMMITS=$COMMITS" >> $GITHUB_OUTPUT

          # อัปเดตตัวนับวันทันที (จะถูก commit ตอนท้าย)
          echo $((DAYS+1)) > .ci/day-count.txt

      - name: Make today's random commits (20–30)
        if: steps.prep.outputs.limit != 'true'
        run: |
          FILE=drip_commits.txt
          touch "$FILE"
          COMMITS=${{ steps.prep.outputs.COMMITS }}

          for ((i=1; i<COMMITS; i++)); do
            echo "Drip commit $i - $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
            git add "$FILE"
            git commit -m "chore: drip commit $i"
            # หน่วงแบบเบา ๆ 30–120 วินาที ต่อ commit
            DELAY=$(( 30 + RANDOM % 91 ))
            echo "⏳ sleep $DELAY sec"
            sleep $DELAY
          done

          # คอมมิตสุดท้ายของวัน + อัปเดตยอดรวม
          TODAY=$COMMITS
          TOTAL=$(cat .ci/total-commits.txt)
          NEW_TOTAL=$((TOTAL + TODAY))
          echo "$NEW_TOTAL" > .ci/total-commits.txt

          echo "Drip commit $TODAY - $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
          git add "$FILE" .ci/day-count.txt .ci/total-commits.txt
          git commit -m "chore: drip commit $TODAY + update counters (day, total)"
          git push

      - name: Summary
        if: steps.prep.outputs.limit != 'true'
        run: |
          echo "### Slow Drip Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Commits today: ${{ steps.prep.outputs.COMMITS }}" >> $GITHUB_STEP_SUMMARY
          echo "- Days completed: $(cat .ci/day-count.txt) / 100" >> $GITHUB_STEP_SUMMARY
          echo "- Total commits so far: $(cat .ci/total-commits.txt)" >> $GITHUB_STEP_SUMMARY

      - name: Finished (already reached 100 days)
        if: steps.prep.outputs.limit == 'true'
        run: echo "Limit reached: 100 days ✔️"
