name: slow-drip

on:
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  drip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: setup git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "sphererom"
          git config user.email "134825090+sphererom@users.noreply.github.com"

      - id: prep
        name: prep
        run: |
          mkdir -p .ci
          [ -f .ci/day-count.txt ] || echo 0 > .ci/day-count.txt
          [ -f .ci/total-commits.txt ] || echo 0 > .ci/total-commits.txt
          DAYS=$(cat .ci/day-count.txt)
          if [ "$DAYS" -ge 100 ]; then
            echo "limit=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          COMMITS=$((20 + RANDOM % 11))
          echo "COMMITS=$COMMITS" >> $GITHUB_OUTPUT
          echo $((DAYS+1)) > .ci/day-count.txt

      - name: run commits
        if: steps.prep.outputs.limit != 'true'
        run: |
          FILE=drip_commits.txt
          touch "$FILE"
          COMMITS=${{ steps.prep.outputs.COMMITS }}
          for ((i=1; i<COMMITS; i++)); do
            echo "Commit $i - $(date -u +%FT%TZ)" >> "$FILE"
            git add "$FILE"
            git commit -m "drip commit $i"
            sleep $((30 + RANDOM % 91))
          done
          TODAY=$COMMITS
          TOTAL=$(cat .ci/total-commits.txt)
          echo $((TOTAL + TODAY)) > .ci/total-commits.txt
          echo "Commit $TODAY - $(date -u +%FT%TZ)" >> "$FILE"
          git add "$FILE" .ci/day-count.txt .ci/total-commits.txt
          git commit -m "drip commit $TODAY update counters"
          git push
